#The website name will appear in several places, the most important one is at the header.
name: Jelly Kingdom
#The website title is used for SEO purposes and set the home page title.
title: Jelly Kingdom | growth, self-development, games and toys
#The website description is used for SEO purposes only.
description: Jelly Kingdom is focus on people growth and development . we share our experient and compare vocational research and artical for people in all ages .
#The website tags are used as keywords for SEO purposes.
tags:
  - blog
  - research
  - games
  - toys
  - growth
  - self-development
#Your home page top banner
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: anthemjelly@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
